fix refreshable blocking node exit
vlio20/utils-decorators pull request #103
Opened 2021-02-21 12:59 UTC by tsachis

2021-02-21 13:28 UTC, vlio20 requested changes
@tsachis please add unit tests.

Maybe this enhancement is also required in other decorators?

2021-02-21 13:28 UTC, vlio20 commented on src/refreshable/refreshable.spec.ts
> +/**
why is that?

2021-02-21 13:28 UTC, vlio20 commented on src/refreshable/refreshable.ts
> +    if (typeof intervalHandler.unref === 'function') {
please add a blank line before the if statement

2021-02-21 13:57 UTC, tsachis commented on src/refreshable/refreshable.spec.ts
> +/**
the default environment in jest is jsdom, which doesn't support the `unref` function in timers. 
`unref` is a node-specific API, so we need to set the environment to `node` so it will be called.

2021-02-21 14:01 UTC, vlio20 commented on src/refreshable/refreshable.spec.ts
> +/**
I see. But maybe we should just mock it? This way you could test that it was called?

2021-02-22 18:53 UTC, tsachis commented on src/refreshable/refreshable.spec.ts
> +/**
You are right. I added the test.

2021-02-22 19:20 UTC, vlio20 approved these changes

2021-02-22 19:21 UTC, merged