fix: Error doesn't catch correctly
vlio20/utils-decorators pull request #142
Opened 2022-04-21 11:05 UTC by gongpeione

<img width="722" alt="image" src="https://user-images.githubusercontent.com/3984824/164444984-9d37d40e-f69d-464b-a3df-a031c9cfeac9.png">

2022-04-21 17:44 UTC, vlio20 commented
Hi @gongpeione can you please create an issue for your PR? I would like to better understand the need for this fix.
Also, please add a unit test.

2022-04-22 03:29 UTC, gongpeione commented
> Hi @gongpeione can you please create an issue for your PR? I would like to better understand the need for this fix. Also, please add a unit test.

Ok, I'll open an issue and add a unit test later, maybe this weekend.

2022-05-01 04:36 UTC, vlio20 commented
@gongpeione  any updates on this one?

2022-05-06 05:59 UTC, vlio20 requested changes

2022-05-06 05:59 UTC, vlio20 commented on src/timeout/timeout.spec.ts
> +  it('should catch original exception after the method throw an error within provided ms', async () => {
Can you also add a test that throws an error after the timeout and make sure that the timeout error is the one that is thrown?

2022-05-06 06:08 UTC, gongpeione commented on src/timeout/timeout.spec.ts
> +  it('should catch original exception after the method throw an error within provided ms', async () => {
Done

2022-05-06 07:25 UTC, merged