Fix `delegate` default serialization with many args
vlio20/utils-decorators pull request #165
Opened 2024-08-04 10:23 UTC by masoud-msk

Looks like a typo in default serialization which is `(...args) => JSON.stringify(...args)` instead of `(...args) => JSON.stringify(args)` as it doesn't work for example in case of the decorated method having more than 3 arguments or more than 2 arguments with the first one not being an object.

2024-08-04 18:06 UTC, vlio20 requested changes

2024-08-04 18:06 UTC, vlio20 commented on package-lock.json
please revert this change

2024-08-04 18:06 UTC, vlio20 commented on src/delegate/delegatify.ts
> +  const keyGenerator: (...args: any[]) => string = keyResolver ?? ((...args) => JSON.stringify(args));
nice catch!

2024-08-07 07:33 UTC, masoud-msk commented on package-lock.json
Done

2024-08-11 05:57 UTC, merged

2024-08-11 06:04 UTC, vlio20 commented
released in 2.0.9. Thanks @masoud-msk